// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.CloudSaveManager
{
    public partial class ProfileData
    {
        public int TotalScore;
        public int MonthlyScore;
        public int TotalBadgesEarned;
        public int SavedStylesThisMonth;

        [Preserve]
        public ProfileData ()
        {
        }
    }
}