// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerDataServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerDataServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<CloudSaveManager.ProfileData> GetOrCreateProfileData()
        {
            return await k_Service.CallModuleEndpointAsync<CloudSaveManager.ProfileData>(
                "CloudSaveManager",
                "GetOrCreateProfileData",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task SaveProfileData(CloudSaveManager.ProfileData data)
        {
            await k_Service.CallModuleEndpointAsync(
                "CloudSaveManager",
                "SaveProfileData",
                new Dictionary<string, object>()
                {
                    {"data", data},
                });
        }

        public async Task<bool> DeletePlayerProfile()
        {
            return await k_Service.CallModuleEndpointAsync<bool>(
                "CloudSaveManager",
                "DeletePlayerProfile",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
